### ISSUE TITLE
I cant get model.json file

### ISSUE THREAD

**Issue by FatemeZamanian** [Hyuto/yolov8-tfjs#3]
Hi 
when i use this cod:
``` model.export(format="tfjs") ```
i got this output :
<img width="339" alt="Screenshot 2023-06-28 at 9 29 16 PM" src="https://github.com/Hyuto/yolov8-tfjs/assets/78360814/0b845495-4704-453e-9407-683dd1fd2077">
but i need this :
<img width="339" alt="Screenshot 2023-06-28 at 9 36 26 PM" src="https://github.com/Hyuto/yolov8-tfjs/assets/78360814/bb03f9dd-335d-4534-81e4-2253ead7465d">

can you help me please?

**Comment by Hyuto** [comment]
Hello, I don't think there is a problem in exporting. I recently try the to export yolov8n model to `tfjs` with 

```py
from ultralytics import YOLO

# Load the model
model = YOLO('yolov8n.pt')  # load a pretrained model
model.export(format='tfjs')
```

And it works just fine. 

![image](https://github.com/Hyuto/yolov8-tfjs/assets/64422277/caeb7637-01d8-400c-97f8-1d92155f084c)

Can I see the full code you use to export?

**Comment by FatemeZamanian** [comment]
Thank you for your answer
The problem was because of the numpy version

**Comment by gassechen** [comment]
```
from ultralytics import YOLO

# Load the model
model = YOLO('yolov8n.pt')  # load a pretrained model
model.export(format='tfjs')

```
Ultralytics YOLOv8.0.196 🚀 Python-3.10.12 torch-2.1.0+cu121 CPU (Intel Xeon 2.00GHz)
YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients

PyTorch: starting from 'yolov8n.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) ((1, 84, 8400), ()) (6.2 MB)

TensorFlow SavedModel: starting export with tensorflow 2.15.0...

ONNX: starting export with onnx 1.15.0 opset 17...
ONNX: simplifying with onnxsim 0.4.35...
ONNX: export success ✅ 2.4s, saved as 'yolov8n.onnx' (12.2 MB)
TensorFlow SavedModel: running 'onnx2tf -i "yolov8n.onnx" -o "yolov8n_saved_model" -nuo --non_verbose'
TensorFlow SavedModel: export failure ❌ 33.4s: generic_type: cannot initialize type "StatusCode": an object with that name is already defined
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
[<ipython-input-22-7a7a1a04879a>](https://localhost:8080/#) in <cell line: 5>()
      3 # Load the model
      4 model = YOLO('yolov8n.pt')  # load a pretrained model
----> 5 model.export(format='tfjs')

11 frames
[/usr/local/lib/python3.10/dist-packages/tensorflow_lite_support/python/task/vision/core/tensor_image.py](https://localhost:8080/#) in <module>
     17 
     18 from tensorflow_lite_support.python.task.vision.core import color_space_type
---> 19 from tensorflow_lite_support.python.task.vision.core.pybinds import image_utils
     20 
     21 

ImportError: generic_type: cannot initialize type "StatusCode": an object with that name is already defined

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------

**Comment by MaryamBoneh** [comment]
hi;
i want convert yolov8m-pose.pt to tfjs format. i used yolo model.export and i get yolov8m-pose_float32.tflite and saved_model.pb and... not like what you get from export .pt to .tfjs.
@Hyuto
